<?php

use Illuminate\Database\Seeder;
use App\Posto;
use Carbon\Carbon;

class PostosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Posto::truncate();
        $postos = [
            [
                'gas_station_cod' => '001', 
                'gas_station_name' => 'Posto Jacutinga',
                'longitude' => (-5.862885),
                'latitude' => (-35.192225),
                'city' => 'Natal',
                'state' => 'RN',
                'show_in_app' => true,
                'last_visit_date' => Carbon::now(),
                'store' => true,
                'oil_change' => true,
                'washing' => false,
                'rubber_repair' => true,
                'common_ethanol' => true,
                'additive_ethanol' => true,
                'common_gasoline' => true,
                'additive_gasoline' => true,
                'premium_gasoline' => false,
                's10_diesel_common' => true,
                's10_diesel_additive' => true,
                's500_diesel_common' => true,
                's500_diesel_additive' => true,
            ],
            [
                'gas_station_cod' => '002', 
                'gas_station_name' => 'Posto Shell rota do Sol',
                'longitude' => (-5.88257),
                'latitude' => (-35.181095),
                'city' => 'Natal',
                'state' => 'RN',
                'show_in_app' => false,
                'last_visit_date' => Carbon::now(),
                'store' => true,
                'oil_change' => true,
                'washing' => true,
                'rubber_repair' => false,
                'common_ethanol' => true,
                'additive_ethanol' => false,
                'common_gasoline' => true,
                'additive_gasoline' => false,
                'premium_gasoline' => true,
                's10_diesel_common' => true,
                's10_diesel_additive' => true,
                's500_diesel_common' => false,
                's500_diesel_additive' => false,
            ],
            [
                'gas_station_cod' => '003', 
                'gas_station_name' => 'Auto Posto Esmeraldo',
                'longitude' => (-5.857018),
                'latitude' => (-35.194856),
                'city' => 'Natal',
                'state' => 'RN',
                'show_in_app' => true,
                'last_visit_date' => Carbon::now(),
                'store' => true,
                'oil_change' => false,
                'washing' => true,
                'rubber_repair' => false,
                'common_ethanol' => true,
                'additive_ethanol' => true,
                'common_gasoline' => true,
                'additive_gasoline' => false,
                'premium_gasoline' => false,
                's10_diesel_common' => true,
                's10_diesel_additive' => true,
                's500_diesel_common' => false,
                's500_diesel_additive' => true,
            ],
            [
                'gas_station_cod' => '004', 
                'gas_station_name' => 'Posto Cirne - Rota do Sol',
                'longitude' => (-5.889975),
                'latitude' => (-35.180173),
                'city' => 'Natal',
                'state' => 'RN',
                'show_in_app' => true,
                'last_visit_date' => Carbon::now(),
                'store' => false,
                'oil_change' => true,
                'washing' => true,
                'rubber_repair' => false,
                'common_ethanol' => true,
                'additive_ethanol' => true,
                'common_gasoline' => true,
                'additive_gasoline' => false,
                'premium_gasoline' => true,
                's10_diesel_common' => true,
                's10_diesel_additive' => true,
                's500_diesel_common' => true,
                's500_diesel_additive' => false,
            ],
            [
                'gas_station_cod' => '005', 
                'gas_station_name' => 'Posto Big Tambaú',
                'longitude' => (-7.11515),
                'latitude' => (-34.825802),
                'city' => 'João Pessoa',
                'state' => 'PB',
                'show_in_app' => true,
                'last_visit_date' => Carbon::now(),
                'store' => true,
                'oil_change' => true,
                'washing' => true,
                'rubber_repair' => false,
                'common_ethanol' => true,
                'additive_ethanol' => true,
                'common_gasoline' => true,
                'additive_gasoline' => true,
                'premium_gasoline' => false,
                's10_diesel_common' => true,
                's10_diesel_additive' => true,
                's500_diesel_common' => false,
                's500_diesel_additive' => true,
            ],
            [
                'gas_station_cod' => '006', 
                'gas_station_name' => 'Posto Grossos',
                'longitude' => (-4.959592),
                'latitude' => (-37.155045),
                'city' => 'Grossos',
                'state' => 'RN',
                'show_in_app' => true,
                'last_visit_date' => Carbon::now(),
                'store' => false,
                'oil_change' => true,
                'washing' => true,
                'rubber_repair' => false,
                'common_ethanol' => true,
                'additive_ethanol' => true,
                'common_gasoline' => true,
                'additive_gasoline' => true,
                'premium_gasoline' => false,
                's10_diesel_common' => true,
                's10_diesel_additive' => true,
                's500_diesel_common' => false,
                's500_diesel_additive' => true,
            ],
        ];
        
        foreach ($postos as $posto) {
            Posto::create($posto);
        }
    }
}
